In [1]:
from PIL import Image
import numpy as np
import cv2


In [2]:
# Load the host and watermark images
hr_image = Image.open("high_resolution_image.jpg")
wm_image = Image.open("./ravenLogo.jpg")

# Resize the watermark image to the same size as the host image
wm_image_resized = wm_image.resize(hr_image.size)

# Convert both images to grayscale
hr_image = hr_image.convert("L")
wm_image_resized = wm_image_resized.convert("L")


In [3]:
U_hr, sigma_hr, V_hr = np.linalg.svd(hr_image)

In [4]:
U_wm, sigma_wm, V_wm = np.linalg.svd(wm_image_resized)

In [5]:
U_wm

array([[ 0.01928185,  0.00605473,  0.00802464, ...,  0.0678824 ,
         0.10627277, -0.1544874 ],
       [ 0.01928185,  0.00605473,  0.00802464, ...,  0.00225156,
         0.00135001,  0.00161912],
       [ 0.01928185,  0.00605473,  0.00802464, ..., -0.13639   ,
        -0.14160791,  0.07312868],
       ...,
       [ 0.01928185,  0.00605473,  0.00802464, ..., -0.01847901,
         0.01124279, -0.00632762],
       [ 0.01928185,  0.00605473,  0.00802464, ...,  0.01471103,
        -0.0347995 ,  0.00156111],
       [ 0.01928185,  0.00605473,  0.00802464, ...,  0.01473661,
        -0.0347757 ,  0.00152805]])

In [6]:
alpha = 0.6
sigma_hr_mod = sigma_hr + alpha * sigma_wm

In [7]:
hr_image_mod = np.dot(U_hr[:, :sigma_hr_mod.shape[0]], np.dot(np.diag(sigma_hr_mod), V_hr[:sigma_hr_mod.shape[0],:]))

In [8]:
hr_image_mod = cv2.normalize(hr_image_mod, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)

In [9]:
img1 = Image.fromarray(hr_image_mod)
img1.show()

In [10]:
img1.save('output_image.png')


# Embedded

In [11]:
U_hr_mod1, sigma_hr_mod1, V_hr_mod1 = np.linalg.svd(hr_image_mod)

In [12]:
U_hr1, sigma_hr1, V_hr1 = np.linalg.svd(hr_image)

In [13]:
U_wm1, sigma_wm1, V_wm1 = np.linalg.svd(np.zeros_like(hr_image))
U_wm1, sigma_wm1, V_wm1


(array([[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]]))

In [14]:
sigma_wm_mod = (sigma_hr_mod - sigma_hr) / alpha

In [15]:
sigma_wm_mod

array([9.39330057e+05, 2.88628913e+04, 2.61896397e+04, ...,
       4.92169268e-11, 3.03312930e-11, 9.03721542e-12])

In [16]:
watermark = np.dot(U_wm[:, :sigma_wm_mod.shape[0]], np.dot(np.diag(sigma_wm_mod), V_wm[:sigma_wm_mod.shape[0],:]))

In [17]:
img=Image.fromarray(watermark)
img.show()