In [1]:
from PIL import Image
import numpy as np
import cv2
hr_image = Image.open("host_image.jpg")
wm_image = Image.open("./watermark_image.jpg")
watermarked_image = Image.open("./output_image-1.png")

# Resize the watermark image to the same size as the host image
wm_image_resized = wm_image.resize(hr_image.size)
watermarked_image_resized = watermarked_image.resize(hr_image.size)

# Convert images to RGB (if not already in that mode)
hr_image = hr_image.convert("RGB")
wm_image_resized = wm_image_resized.convert("RGB")
watermarked_image_resized = watermarked_image_resized.convert("RGB")

# Split images into R, G, B channels
hr_r, hr_g, hr_b = hr_image.split()
wm_r, wm_g, wm_b = wm_image_resized.split()
hr_r_mod, hr_g_mod, hr_b_mod = watermarked_image_resized.split()

# Convert channels to numpy arrays
hr_r = np.array(hr_r)
wm_r = np.array(wm_r)
hr_r_mod = np.array(hr_r_mod)
hr_r,wm_r,hr_r_mod

(array([[13, 13, 12, ..., 10, 10, 10],
        [13, 12, 12, ..., 10,  9, 10],
        [13, 12, 12, ..., 10, 10,  9],
        ...,
        [ 0,  0,  0, ...,  1,  1,  1],
        [ 0,  0,  0, ...,  1,  1,  1],
        [ 0,  0,  0, ...,  1,  1,  1]], dtype=uint8),
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
 array([[15, 15, 14, ...,  6,  6,  6],
        [15, 14, 14, ...,  6,  6,  6],
        [15, 14, 14, ...,  6,  6,  6],
        ...,
        [ 2,  2,  3, ...,  1,  1,  1],
        [ 2,  3,  3, ...,  1,  1,  1],
        [ 2,  2,  3, ...,  1,  1,  1]], dtype=uint8))

In [2]:
U_hr_mod, sigma_hr_mod, V_hr_mod = np.linalg.svd(hr_r_mod)
U_hr_mod, sigma_hr_mod, V_hr_mod

(array([[ 0.00784158,  0.0165516 ,  0.01252618, ..., -0.03089241,
          0.00452719, -0.02775651],
        [ 0.00785762,  0.0165771 ,  0.01250698, ...,  0.02490659,
         -0.01906858,  0.00916064],
        [ 0.00788229,  0.01655556,  0.01255978, ..., -0.01606805,
          0.04317793,  0.02777074],
        ...,
        [ 0.00295465,  0.00965043, -0.00166323, ..., -0.0183748 ,
          0.01678197,  0.0147971 ],
        [ 0.00295669,  0.00977461, -0.00210373, ...,  0.06505869,
         -0.0063734 , -0.01037638],
        [ 0.00295312,  0.00982364, -0.00224426, ..., -0.05579352,
          0.00268234, -0.00980855]]),
 array([4.02619575e+05, 5.18654521e+04, 3.54809060e+04, ...,
        6.50500237e+00, 6.44696324e+00, 6.38079693e+00]),
 array([[ 0.0050571 ,  0.00505493,  0.00506765, ...,  0.00141815,
          0.00141826,  0.00141982],
        [-0.00946759, -0.00943624, -0.00942743, ...,  0.0058904 ,
          0.00589847,  0.00589712],
        [ 0.00423957,  0.00419411,  0.00417849, ..

In [3]:
U_hr, sigma_hr, V_hr = np.linalg.svd(hr_r)
U_hr, sigma_hr, V_hr

(array([[ 0.00786463,  0.01658912,  0.01261302, ..., -0.02818943,
          0.00583464, -0.00172789],
        [ 0.00787961,  0.01661528,  0.01260278, ...,  0.02942328,
          0.02990887,  0.0318253 ],
        [ 0.00790425,  0.01659921,  0.01264274, ...,  0.00549401,
         -0.0460175 , -0.02067673],
        ...,
        [ 0.002987  ,  0.00970317, -0.00157889, ..., -0.00786459,
          0.00408086,  0.01938412],
        [ 0.00298716,  0.00983045, -0.00200638, ...,  0.0020571 ,
         -0.00418084, -0.01177685],
        [ 0.00298414,  0.00988038, -0.00214879, ...,  0.00196834,
         -0.00239647,  0.00274538]]),
 array([4.30179881e+05, 9.97528875e+04, 6.19978435e+04, ...,
        8.13821147e+00, 8.08042711e+00, 7.88048870e+00]),
 array([[ 0.00507577,  0.00507415,  0.00508763, ...,  0.00144267,
          0.00144328,  0.00144515],
        [-0.00946242, -0.00942319, -0.00941631, ...,  0.00592094,
          0.00592245,  0.00591067],
        [ 0.00419669,  0.00416229,  0.00413792, ..

In [4]:
U_wm, sigma_wm, V_wm = np.linalg.svd(wm_r)
U_wm, sigma_wm, V_wm

(array([[ 0.01948359,  0.00632362,  0.0078601 , ..., -0.17387204,
         -0.09598725,  0.23983445],
        [ 0.01948359,  0.00632362,  0.0078601 , ...,  0.00565323,
         -0.00146993, -0.00271475],
        [ 0.01948359,  0.00632362,  0.0078601 , ...,  0.08876057,
         -0.01581434, -0.0972584 ],
        ...,
        [ 0.01948359,  0.00632362,  0.0078601 , ..., -0.04144451,
          0.04503448, -0.01459258],
        [ 0.01948359,  0.00632362,  0.0078601 , ..., -0.02173973,
         -0.01445928,  0.03631894],
        [ 0.01948359,  0.00632362,  0.0078601 , ..., -0.02180126,
         -0.01449224,  0.03642176]]),
 array([9.29320997e+05, 4.54986381e+04, 4.14095771e+04, ...,
        6.38236386e-11, 3.62855865e-11, 1.20220457e-11]),
 array([[ 1.44965486e-02,  1.44965486e-02,  1.44965486e-02, ...,
          1.44965486e-02,  1.44965486e-02,  1.44965486e-02],
        [-8.55295299e-04, -8.55295299e-04, -8.55295299e-04, ...,
         -8.55295299e-04, -8.55295299e-04, -8.55295299e-04],
  